services:
  redis-node-1:
    hostname: redis-node-1
    container_name: redis-node-1
    image: bitnami/redis-cluster:latest # network 생성시 cluster_* prefix 강제 추가되어 맨밑 networks 설정에 external, name 추가
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_CLUSTER_CREATOR=yes # 이 노드가 클러스터를 생성
      - REDIS_CLUSTER_REPLICAS=1 # 각 마스터에 하나의 슬레이브 노드 생성
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 redis-node-7:6379
    ports:
      - "6300:6379"
    networks:
      - redis-cluster-network

  redis-node-2:
    hostname: redis-node-2
    container_name: redis-node-2
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 redis-node-7:6379
    ports:
      - "6301:6379"
    networks:
      - redis-cluster-network

  redis-node-3:
    hostname: redis-node-3
    container_name: redis-node-3
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 redis-node-7:6379
    ports:
      - "6302:6379"
    networks:
      - redis-cluster-network

  redis-node-4:
    hostname: redis-node-4
    container_name: redis-node-4
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_REPLICATION_MODE=slave
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 redis-node-7:6379
    ports:
      - "6303:6379"
    networks:
      - redis-cluster-network

  redis-node-5:
    hostname: redis-node-5
    container_name: redis-node-5
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_REPLICATION_MODE=slave
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 redis-node-7:6379
    ports:
      - "6304:6379"
    networks:
      - redis-cluster-network

  redis-node-6:
    hostname: redis-node-6
    container_name: redis-node-6
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_REPLICATION_MODE=slave
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 redis-node-7:6379
    ports:
      - "6305:6379"
    networks:
      - redis-cluster-network

  redis-node-7:
    hostname: redis-node-7
    container_name: redis-node-7
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_REPLICATION_MODE=slave
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 redis-node-7:6379
    ports:
      - "6306:6379"
    networks:
      - redis-cluster-network

  predixy:
    hostname: predixy
    container_name: predixy
    image: haandol/predixy:latest
    ports:
      - "7617:7617"
    volumes:
      - ./conf:/etc/predixy/conf
    networks:
      - redis-cluster-network
    depends_on:
      - redis-node-1
      - redis-node-2
      - redis-node-3
      - redis-node-4
      - redis-node-5
      - redis-node-6
      - redis-node-7

networks:
  redis-cluster-network:
    name: mybridge
    external: true
    driver: bridge
