services:
  redis-node-1:
    hostname: redis-node-1
    container_name: redis-node-1
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_CLUSTER_CREATOR=yes # 이 노드가 클러스터를 생성
      - REDIS_CLUSTER_REPLICAS=1 # 각 마스터에 하나의 슬레이브 노드 생성
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 redis-node-7:6379
    ports:
      - "6300:6379"
    networks:
      - mybridge

  redis-node-2:
    hostname: redis-node-2
    container_name: redis-node-2
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 redis-node-7:6379
    ports:
      - "6301:6379"
    networks:
      - mybridge

  redis-node-3:
    hostname: redis-node-3
    container_name: redis-node-3
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 redis-node-7:6379
    ports:
      - "6302:6379"
    networks:
      - mybridge

  redis-node-4:
    hostname: redis-node-4
    container_name: redis-node-4
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_REPLICATION_MODE=slave
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 redis-node-7:6379
    ports:
      - "6303:6379"
    networks:
      - mybridge

  redis-node-5:
    hostname: redis-node-5
    container_name: redis-node-5
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_REPLICATION_MODE=slave
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 redis-node-7:6379
    ports:
      - "6304:6379"
    networks:
      - mybridge

  redis-node-6:
    hostname: redis-node-6
    container_name: redis-node-6
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_REPLICATION_MODE=slave
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 redis-node-7:6379
    ports:
      - "6305:6379"
    networks:
      - mybridge

  redis-node-7:
    hostname: redis-node-7
    container_name: redis-node-7
    image: bitnami/redis-cluster:latest
    environment:
      - REDIS_REPLICATION_MODE=slave
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_NODES=redis-node-1:6379 redis-node-2:6379 redis-node-3:6379 redis-node-4:6379 redis-node-5:6379 redis-node-6:6379 redis-node-7:6379
    ports:
      - "6306:6379"
    networks:
      - mybridge

networks:
  mybridge:
    driver: bridge
