networks:
  replica:
    driver: bridge

services:
  redis:
    container_name: redis
    image: redis:7.2-alpine
    ports:
      - 6379:6379
    networks:
      - replica
    restart: always

  replica:
    container_name: replica
    image: redis:7.2-alpine
    ports:
      - 6378:6379
    networks:
      - replica
    volumes:
      - ./conf:/usr/local/etc/redis/
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always

  replica2:
    container_name: replica2
    image: redis:7.2-alpine
    ports:
      - 6377:6379
    networks:
      - replica
    volumes:
      - ./conf:/usr/local/etc/redis/
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
